vich_uploader:
    db_driver: orm  # This is REQUIRED - can be 'orm', 'mongodb' or 'phpcr'

    mappings:
        product_image:  # This can be any name you want
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true